FROM brevdev/ubuntu-proxy:0.1.14
# FROM rocker/rstudio-stable:3.5.2
# In reality, we just use the base image for proxy and the application is run in docker with the correct setup instructions (see application database item)